version: "3.9"

services:
  postgres:
    env_file:
      - path: ./default.env
        required: true # default
      - path: ./override.env
        required: false
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
  wikigraph:
    container_name: wikigraph
    stdin_open: true
    tty: true
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./:/wikigraph
      - wikigraph-target:/diesel/target
    depends_on:
      - postgres

volumes:
  postgres:
  wikigraph-target:
